[[headers]]
for = "/"
[headers.values]
Link = [
"</src.*.css> rel=preload as=stylesheet",
"</src.*.js> rel=preload as=script",
"</*.webp> rel=preload as=image",
"</*.jpg> rel=preload as=image",
"</*.png> rel=preload as=image"
]
[[headers]]
for = "/*"
[headers.values]
[[redirects]]
from = "/*"
to = "/index.html"
status = 200
[build.environment]
  NODE_VERSION = "20"
  PYTHON_VERSION = "2.7"
  NPM_FLAGS = "--unsafe-perm=true"

